// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snmriwohxstirzspnjxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNubXJpd29oeHN0aXJ6c3BuanhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDk4MzksImV4cCI6MjA2ODE4NTgzOX0.GckX4kZo7agxRb25ehjkoFaIJ-xuo7DZOZo-h-dsYaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});